### ISSUE TITLE
T-ETH-Elite with ESPHome

### ISSUE THREAD

**Issue by pixelwave** [Xinyuan-LilyGO/LilyGO-T-ETH-Series#87]
I have a question regarding the T-ETH-Elite pin layout.

For ESPHome integration I need the following PIN definition:

```
# Example configuration entry for SPI chips
ethernet:
  type: W5500
  clk_pin: GPIOXX
  mosi_pin: GPIOXX
  miso_pin: GPIOXX
  cs_pin: GPIOXX
  interrupt_pin: GPIOXX
  reset_pin: GPIOXX
```

In the item description you mention **ETH_RST pin = -1**.

That is not acceptable in ESPHome definition. I need an actual PIN.

What should I put as ETH_RST pin?
