### ISSUE TITLE
T-POE Pro | Ethernet Timeout - Will NOT Connect but power works.

### ISSUE THREAD

**Issue by CopperHeroin** [Xinyuan-LilyGO/LilyGO-T-ETH-Series#97]
I think I may have a faulty board. I Have tried just about everything ChatGPT and I can think of as to why the ethernet port will not work. Wifi works but If I plug the board in via ethernet it will power on but no yaml setting combinations I can find will work and there is a surprisingly small amount of information available on this board and how to configure it. I purchased this so I could power the board with POE and use an ethernet connection so if the board is faulty I have to return it.  That being said... am I missing something here? Thanks guys!

\\YAML

esphome:
  name: esphome-web-f168ec
  friendly_name: HVAC Controller
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN  # Adjust as needed
  phy_addr: 0
  manual_ip:
    static_ip: 192.168.1.22
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 8.8.8.8

![Capture](https://github.com/user-attachments/assets/b30a7b74-2899-442a-8157-6960282785d6)
<img width="914" alt="Screenshot 2025-01-07 at 5 10 21 PM" src="https://github.com/user-attachments/assets/e58fa2dd-5052-4b52-8077-3eca0268cab8" />

**Comment by lewisxhe** [comment]
Test this
```
esphome:
  name: t-eth-pro
  friendly_name: t-eth-pro

esp32:
  board: esp32dev
  framework:
    type: arduino

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_OUT
  phy_addr: 0
  reset_pin: 5

  # Optional manual IP
  # manual_ip:
  #   static_ip: 192.168.36.227
  #   gateway: 192.168.36.1
  #   subnet: 255.255.255.0


# Enable logging
logger:
  level: DEBUG
  baud_rate: 115200
  logs:
    mqtt.component: DEBUG
    mqtt.client: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: "dBVA+/ahpgURrxBUQ2pbJzNA9b4U/9Yk8wntuW8tJzY="

```
